export const tailwindConfig = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#4a4e4a",
        "surface-container-low": "#f5f1ea",
        "error-container": "#ffdad8",
        "primary-fixed": "#c8e8d0",
        "on-error-container": "#690005",
        "inverse-on-surface": "#f5f0e8",
        "on-surface": "#2e3230",
        "tertiary-container": "#c4a66a",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#8ecf9e",
        "tertiary-fixed": "#f8e0a8",
        "surface-container-high": "#eae6de",
        secondary: "#6b6358",
        "on-secondary-fixed": "#1e1a13",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        outline: "#74796e",
        error: "#b83230",
        "surface-tint": "#4a7c59",
        "primary-container": "#78a886",
        "on-primary-fixed": "#002110",
        "surface-container": "#f0ece4",
        background: "#faf6f0",
        "surface-bright": "#faf6f0",
        "on-secondary-fixed-variant": "#4a4538",
        "surface-dim": "#dbd7cf",
        "surface-container-highest": "#e4e0d8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#554020",
        "on-background": "#2e3230",
        primary: "#4a7c59",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3230",
        tertiary: "#705c30",
        "on-tertiary-fixed": "#221a05",
        "outline-variant": "#c4c8bc",
        "on-tertiary-container": "#554020",
        "secondary-container": "#f0e8db",
        "on-secondary-container": "#5e5548",
        "tertiary-fixed-dim": "#dcc48e",
        "surface-variant": "#e4e0d8",
        surface: "#faf6f0",
        "secondary-fixed": "#f0e8db",
        "secondary-fixed-dim": "#d4ccbf",
        "inverse-primary": "#8ecf9e",
        "on-primary-fixed-variant": "#2a6038",
        "on-primary-container": "#d8f0de",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Literata"],
        display: ["Literata"],
        body: ["Nunito Sans"],
        label: ["Nunito Sans"],
      },
    },
  },
};
